# Generated by Django 4.2.2 on 2023-06-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='sector_image',
            field=models.ImageField(blank=True, null=True, upload_to='sector_images'),
        ),
    ]
